myprops: #自定义的属性和值
  #原来的配置
#  simpleprop: D:\VS\git\jgzw\service-building\src\main\resources\view.json
  simpleprop: E:\project_develop\gm\08_应用服务\jgzw\service-building\src\main\resources\view.json
  #simpleprop: D:\software\tomcat\building\view.json
  systemid :  5CC0556BAD2345E0A131DFA37002BDEB

spring:
  aop:
    auto: true
    proxy-target-class: true
  profiles:
    # 选择配置文件
    active: test
  servlet:
    #设置文件上传大小限制
    multipart:
      #单个文件最大（-1是不做限制）
      max-file-size: -1
      #设置总上传数据总大小
      max-request-size: -1

  # jackson
  jackson:
    # 设置时间的时区
    time-zone: GMT+8
    # 设置时间的统一出库格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 配置完成后，所有通过@responseBody（或者@restController）转json的，都将不返回为空字段,在Spring Boot 中的application.yml配置全局定义， 这种默认都生效
    # JsonInclude.Include.ALWAYS              默认
    # JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
    # JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
    # JsonInclude.Include.NON_NULL           属性为NULL   不序列化
    default-property-inclusion: ALWAYS

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/static/

#undertow
#server:
#  undertow:
#    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
#    io-threads: 16
#    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
#    worker-threads: 256
#    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
#    # 每块buffer的空间大小,越小的空间被利用越充分
#    buffer-size: 1024
#    # 是否分配的直接内存
#    direct-buffers: true

#文件上传默认值设置
attach:
  fpf-name: attach/building/
  prof-name: 附件
  url: D:/Collection/files/${attach.fpf-name}
  temp-url: D:/Collection/files/temp/
  status:
    used: "01"
    unused: "00"

#mybatis-plus配置
mybatis-plus:
  #MyBatis 配置文件位置
  config-location: classpath:mapper/mybatis-config.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*/*/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.lzctzk.address.dao.building.entity;com.lzctzk.address.pojo.*.entity;
  global-config:
    #刷新mapper 调试神器
    refresh: true
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: uuid
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断",NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      #数据库类型
      db-type: oracle
      #是否开启大写命名，默认不开启
      capital-mode: false
      #是否开启 LIKE 查询，即根据 entity 自动生成的 where 条件中 String 类型字段 是否使用 LIKE，默认不开启
      column-like: false
  #configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    #map-underscore-to-camel-case: true
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    #cache-enabled: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    #jdbc-type-for-null: 'null'


